server:
  port: 12000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DylanPeng123/bearbear-config.git
          username: DylanPeng123
          password: WXHFMYZC123gh
  # 配置rabbitmq信息；如果是都与默认值一致则不需要配置
  rabbitmq:
    host: 192.168.81.130
    port: 5672
    username: admin
    password: p@ssw0rd
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
management:
  endpoints:
    web:
      exposure:
        # 暴露触发消息总线的地址
        include: bus-refresh